Including html forms in markdown
adobe/helix-html2md pull request #380
Opened 2024-01-19 18:09 UTC by jalagari

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues #379 

Thanks for contributing!

2024-01-19 21:58 UTC, tripodsan requested changes
sorry, but this is cannot be supported as it doesn't conform the markup semantics of the helix pipeline.

2024-01-29 15:09 UTC, jalagari commented
Discussion at https://cq-dev.slack.com/archives/C05QU7MMRNF/p1705690163398589

2024-02-02 11:14 UTC, trieloff requested changes
Let's find a way that is architecturally consistent with the overall Helix ecosystem.

2024-02-02 11:14 UTC, trieloff commented on src/process-forms.js
> +                  value: JSON.stringify(formDef),
We should not dump raw JSON into the content bus.

2024-12-04 10:33 UTC, closed without merging